# Generated by Django 5.0.6 on 2024-07-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='password1',
            field=models.CharField(default=123, max_length=60),
            preserve_default=False,
        ),
    ]
