# Generated by Django 5.0.6 on 2024-07-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sign_password1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log',
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
