# Generated by Django 5.0.6 on 2024-07-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_log_delete_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('categroy', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('duration', models.CharField(max_length=120)),
                ('info', models.CharField(max_length=200)),
                ('button', models.CharField(max_length=100)),
            ],
        ),
    ]
