# Generated by Django 5.0.6 on 2024-07-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_course_categroy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categroy',
        ),
        migrations.AddField(
            model_name='course',
            name='practicalcategroy',
            field=models.BooleanField(default=False),
        ),
    ]
