# Generated by Django 5.0.6 on 2024-07-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_course_categroy_course_practicalcategroy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='practicalcategroy',
            new_name='practical',
        ),
    ]
