# Generated by Django 5.0.6 on 2024-07-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_sign_up_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up_table',
            old_name='user',
            new_name='main',
        ),
    ]
