# Generated by Django 5.0.6 on 2024-07-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_user_sign_up_table_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up_table',
            old_name='mobile_no',
            new_name='mobile',
        ),
    ]
