# Generated by Django 5.0.7 on 2024-08-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_mobile_no_sign_up_table_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up_table',
            name='add',
            field=models.CharField(default=-2021, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign_up_table',
            name='city_name',
            field=models.CharField(default=-2021, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign_up_table',
            name='collge_name',
            field=models.CharField(default=-2021, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign_up_table',
            name='f_name',
            field=models.CharField(default=-2021, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign_up_table',
            name='p_email',
            field=models.CharField(default=-2021, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign_up_table',
            name='p_mobile',
            field=models.CharField(default=-2021, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign_up_table',
            name='pincode',
            field=models.IntegerField(default=-2021, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign_up_table',
            name='profile_pic',
            field=models.ImageField(default=-2021, upload_to='profiles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign_up_table',
            name='qualification',
            field=models.CharField(default=-2021, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign_up_table',
            name='s_name',
            field=models.CharField(default=-2021, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign_up_table',
            name='state',
            field=models.CharField(default=-2021, max_length=50),
            preserve_default=False,
        ),
    ]
