# Generated by Django 5.0.7 on 2024-08-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_sign_up_table_add_sign_up_table_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up_table',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
